tokens_left_text='xpath=(//XCUIElementTypeStaticText[@name="TOKENS LEFT"]/following-sibling::XCUIElementTypeStaticText)[5]'
first_news_article = '//XCUIElementTypeStaticText[@name="News"]/preceding-sibling::XCUIElementTypeStaticText[2]'
news_title = '//XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeStaticText'
news_detail_text = '//XCUIElementTypeStaticText[@name="news detail"]'
redeem_your_token_button = 'xpath=//XCUIElementTypeTable/XCUIElementTypeCell[1]/XCUIElementTypeButton[3]'
insufficient_balance_message = 'xpath=//XCUIElementTypeStaticText[@name="Insufficient Balance !!!"]'
you_have_redeemed_coins_message = '//XCUIElementTypeStaticText[@name="HEY! YOU HAVE REDEEMED YOUR COINS."]'
first_redeem_button = 'xpath=(//XCUIElementTypeButton[@name="REDEEM"])[1]'
terms_condition_warning = '//XCUIElementTypeStaticText[@name="Please accept our T&C before proceeding further."]'
coupen_code_text = '//XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeStaticText'
knight_tv_text = '//XCUIElementTypeStaticText[@name="Knights TV"]'
flrp_like_icon = '//XCUIElementTypeOther/XCUIElementTypeButton[@name="flrp like icon"]'