popup_skip_button = '//XCUIElementTypeStaticText[@name="Hey Steve, 20% off on next flight for you ! Use Coupon code MY200"]'
photo_details = '//XCUIElementTypeButton[@name="photos detail"]'
loyalty_button = '//XCUIElementTypeButton[@name="LOYALTY"]'
fan_chat = '//XCUIElementTypeButton[@name="FAN CHAT"]'
kkr_logo_main = '//XCUIElementTypeButton[@name="logo main"]'
home_button = '//XCUIElementTypeButton[@name="HOME"]'
fixtures_button = '//XCUIElementTypeButton[@name="FIXTURES"]'
tab_bar = '//XCUIElementTypeTabBar[@name="Tab Bar"]'
clips_button = '//XCUIElementTypeButton[@name="CLIPS"]'
menu_button = '//XCUIElementTypeButton[@name="MENU"]'
gaming_hub = '//XCUIElementTypeStaticText[@name="GAMING HUB"]'
navigation_bar = '//XCUIElementTypeNavigationBar[@name="KKR_App.RootBaseTabbar"]'
user_icon = '//XCUIElementTypeButton[@name="T"]'
news_menu = '//XCUIElementTypeStaticText[@name="NEWS"]'
news_first_article = '//XCUIElementTypeTable/XCUIElementTypeCell[1]'

tokens_earned = '//XCUIElementTypeStaticText[@name="TOKENS LEFT"]/following-sibling::XCUIElementTypeStaticText[5]'
tokens_left = '//XCUIElementTypeStaticText[@name="TOKENS LEFT"]/preceding-sibling::XCUIElementTypeStaticText[1]'

