ipldropdown_val = '//span[contains(text(),"Points Table")]'
accordin_loc = '//button[@id ="standingsAccordion2"]'
matchcard_loc_first = '((//div[@class="match-listing"])[3]//div[@class="match-details"])[3]'
matchcentertext = '//div[@class="team team-won team-a"]//span[@class="score"]'
matchscoretest = '(//div[@class="match-listing"])[1]/descendant::div[@class="match-details"]'