elite_membership_card = '//div[contains(@class,"card")]/label[@for="elite-membership"]'
pro_membership_card = '//div[contains(@class,"card")]/label[@for="pro-membership"]'
junior_membership_card = '//div[contains(@class,"card")]/label[@for="junior-membership"]'
next_button = '//button[normalize-space()="NEXT"]'
delivery_address = '//textarea[@placeholder="Delivery Address"]'
pincode_purchasemembership = '//input[@name="pincode"]'
country_field = '//select[@id="country"]'
state_field = '//select[@id="state"]'
city_field = '//input[@name="city"]'
jerseysize_loc = '//select[@id="jerseysize"]'
purchasemembership_btn = '//span[text()="Purchase Membership"]'
bankloc = '(//span[contains(text(),"Net Banking")])[2]'
netbank_dropdown = '//select[@id="netBankingBank"]'
make_payment = '(//a[@id="SubmitBillShip"])[3]'
send_response = '//button[@type="submit h-center"]'
success_message = '//p[contains(text(),"Success")]'
payment_done = '(//span[contains(text(),"Done")])[1]'
purchasemembership_txt = '//span[contains(text(),"See all benefits")]'
payment_page_txt = '//span[contains(text(),"Payment Information")]'
congratualtion_txt = '//h3[contains(text(),"Congratulations!")]'
dynamicmembership = '//div[contains(@class,"card")]/label[@for="membership-type"]'
Junior_Firstname = '//input[@id="firstName"]'
junior_lastname ='//input[@id="lastName"]'
junior_dob = '//input[@id="DOB"]'
male_radio_btn = '//input[@id="male"]'
female_radio_btn = '//input[@id="female"]'
step_1_txt = "//span[text()='Step 1']"
membership_name = "//span[text()='Membership']"
Join_now_btn1 = '//span[@class="btn-text" and text()="join now"]/ancestor::div[@class="masthead-content"]'
Pro_membership_title = '//span[@class="tab-text" ]/ancestor::li[@class="tab-name tab-tab-pro-membership active"]'
Elite_membership_title = '//span[@class="tab-text" ]/ancestor::li[@class="tab-name tab-tab-elite-membership"]'
junior_membership_title = '//h3[text()="Junior membership"]'
Join_now_pro_elite = '//div[@class="programme-footer"]//button[@class="btn btn-fill"]'
gift_now_btn = '//span[text()="Gift now"]/ancestor::button[@class="btn btn-fill"]'
pro_choose_plan = '//td[@class="table-data"]//button[@type="button"]'
elite_choose_plan = '//td[@class="table-data table-data-elite"]//button[@type="button"]'
junior_dob = '//input[@id="DOB"]'
male_radio_btn = '//input[@id="male"]'
female_radio_btn = '//input[@id="female"]'
other_radio_btn = '//input[@id="other"]'
next_btn_congrats_screen = "//span[text()='NEXT']"
purchasemembership_joinbtn = "//div[@class='masthead-content']//button[@type='button']"


