latestnav= '//span[contains(text(),"Latest")]'
newsoption ='(//span[contains(text(),"News")])[1]'
twitter_option = '(//button[@aria-label="Share on Twitter"])[1]'
shareoption_newspage = '(//button[@aria-label="Share"])[1]'
copylink_option = '(//button[@aria-label="Copy Link"])[1]'
social_iconloc ='//div[@class="social-items datalayer-share"]'
