ipl_titlenav = '//span[contains(text(),"IPL 2024")]'
matchesdropdown_val = '//span[contains(text(),"Matches")]'
filter_iplpage = '//div[@class="filter-section datalayer-filter"]/button[@class="btn btn-more"]/span[text()="Filter"]'
filter_year = '//p[contains(text(),"Filter by Year")]'
apply_filteroption ='//span[contains(text(),"Apply Filters")]'
ipl_yeardropdownval = '//button[contains(text(),"2023")]'
ipl_data2023 ='//span[contains(text(),"May 19, 2023")]'
filter_team ='//p[contains(text(),"Filter by Teams")]'
filter_teamval = '//button[contains(text(),"Kolkata Knight Riders")]'
kkr_text ='//p[contains(text(),"Kolkata Knight Riders")]'
filter_status ='//p[contains(text(),"Filter by Status")]'
filter_statusval ='//button[contains(text(),"Upcoming")]'
filter_resetbtn ='//div[@class="footer"]//span[@class="btn-text"][normalize-space()="Reset Filters"]'
filter_upcomingtxt ='//span[contains(text(),"Upcoming")]'
filter_rrtxt ='//img[@alt="Rajasthan Royals"]'