complete_profile_list = '//div[@class="form-element"]'
mobile_number_field = '//div[@class="mobile-number"]//input'
first_name_field = '//input[@id="First Name"]'

last_name_field = '//input[@id="Last Name"]'
email_id_field = '//input[@type="email"]'
date_of_birth_field = '//input[@placeholder="Date of Birth"]'

login_button = '//span[contains(text(),"Login")]'
mobile_number_field_1 = '//input[@id="Mobile_number"]'
whatsapp_no_button = '//button[@aria-label="no"]'
whatsapp_yes_button = '//button[@aria-label="yes"]'

send_sms_button = '//span[text()="Send OTP via SMS"]'
otp_less_button = '//button[@id="otpless"]'
otp_less_iframe = '//iframe[@id="otpless-floating-frame"]'

country_dropdown = '//select[@name="Country DropDown"]'
gender_female_radio_button = '(//input[@value="female"])[1]'
submit_button = '//span[contains(text(),"Submit")]'
terms_checkbox = '//input[@type="checkbox" and @name="Terms and Conditions"]'

skip_button = '//a[text()="skip"]'
otp_input = '//div[@class="otp-wrap"]/div/input[@name="otp"]'
purchase_membership_heading = '//h2[text()="Purchase Membership"]'
send_otp_button ='//span[contains(text(),"Send OTP via SMS")]'
failed_message = '(//span[contains(text(),"Failed")])[2]'
error_message ='//span[contains(text(),"Invalid Mobile Number")]'
mobile_number_loc ='//input[@type="input"]'
whatsapp_icon_frame ='//div[@class="dsp-fl justify-center align-center w-100 h-100 pos-rel"]'
whatsapp_icon = '//div[@class="dsp-fl justify-center align-center w-50px h-50px br-100 full-border curs-point"]//img'
whatsapp_barcode = '//div[@class="dsp-fl w-35 h-100"]'
pincode_field = '//input[@type="text" and @id="pin-code"]'
emailid_error_message = '//span[contains(text(),"Email Id already exist")]'
city_loc ='//input[@type="text" and @placeholder="City"]'
state_loc ='//input[@id="state"]'
